import Head from "next/head"
import { useEffect, useRef, useState } from "react"
import styles from "styles/Home.module.css"
import { disableBodyScroll, enableBodyScroll } from "body-scroll-lock"

export default function Home() {
  const [test, setTest] = useState(false)
  const $header = useRef()
  useEffect(() => {
    const header = $header.current
    if (test) {
      disableBodyScroll(header)
    } else {
      enableBodyScroll(header)
    }
  }, [test])
  return (
    <div>
      <Head>
        <title>NextJs Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header ref={$header}>
        <nav className={styles.header}>
          <ul>
            <li>First</li>
            <li>Second</li>
            <li>Third</li>
          </ul>
          <button
            onClick={() => {
              setTest(!test)
            }}
          >
            123
          </button>
        </nav>
      </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> demo!
        </h1>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
