import Head from "next/head"
import { useEffect, useRef, useState } from "react"
import styles from "styles/Home.module.css"
import {scrollBlock} from 'utils/scrollBlock';


export default function Home() {
  const [test, setTest] = useState(false)
  const yPos = useRef(0)

  const scrollBlockHelper = status => {
    const body = document.querySelector('body');
    if (status) {
      yPos.current = window.scrollY;
      scrollBlock(true, body, null);
    } else {
      scrollBlock(false, body, null, yPos.current, null);
      yPos.current = 0;
    }
  };

  useEffect(() => {
    scrollBlockHelper(test);
  }, [test])
  return (
    <div>
      <Head>
        <title>NextJs Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav className={styles.header}>
          <ul>
            <li>First</li>
            <li>Second</li>
            <li>Third</li>
          </ul>
          <button
            onClick={() => {
              setTest(!test)
            }}
          >
            123
          </button>
        </nav>
      </header>
      <main className={styles.main}>
        {new Array(100).fill().map((item, i) => (
          <div key={i} className={styles.block}>{i}</div>
        ))}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
